# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0002_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
